#
# What to change?
#   Trigger to the workflow (push, pull_request...) and branch
#   Add necessary secrets to repo if not already added
#   Specify correct region of the ECR image in the "Get docker token" step
#   Add image URI from the ECR repository in the on-success job
#
name: Pull AWS ECR image for use

on:
  push:
    branches:
      - $default-branch

jobs:
  authenticate_container:
    name: authenticate_docker
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get_ecr_token.outputs.ecr_token }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEVOPS_TF_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEVOPS_TF_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Get docker token
        run: echo "::set-output name=ecr_token::$(aws ecr get-login-password --region us-east-2)"
        id: get_ecr_token

  on-success:
    name: Run steps in the container
    runs-on: ubuntu-latest
    needs: authenticate_container
    container: 
      image: <Image URI>
      credentials:
        username: AWS
        password: ${{ needs.authenticate_container.outputs.token }}
    steps:
      - name: Simple step
        run: echo "ECR authentication successful" > result.txt
      
      # Add more steps to be executed in the container here
      #
      #